# Generated by Django 2.2.4 on 2019-09-02 00:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190901_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='data',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/dataFiles'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
