# Generated by Django 2.2.4 on 2019-09-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190901_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='data',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
