# Generated by Django 2.2.5 on 2019-09-04 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190903_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
