# Generated by Django 2.2.5 on 2019-09-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190906_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
